# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']

  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kconfig': '@latest'
    'frameworks/ki18n': '@latest'
    'frameworks/kcoreaddons': '@latest'
    'maui/mauikit': '@latest'
    'pim/akonadi-contacts' : '@stable'
    'pim/akonadi-calendar' : '@stable'
    'pim/calendarsupport' : '@stable'
    'pim/eventviews' : '@stable'
